// "Luna Glass" UI style for forza-MIT: Windows XP Luna chrome (blue title bars, beige faces, green Start
// buttons, red close buttons, balloon tooltips) blended with modern dark glass HUD panels, pixel digits
// (Silkscreen + Press Start 2P) and dot-matrix readouts (Doto). Pure Slate, no assets.
//
// Files it loads at runtime (see tools/ui/README.md):
//   <Project>/UI/Generated/*.png   brushes, generated by tools/ui/make_ui_assets.py (gitignored, regenerate)
//   <Project>/UI/Fonts/*.ttf       OFL fonts, fetched by tools/ui/fetch_fonts.py (committed)
//
// Usage:
//   FCambridgeUIStyle::Get()                      the registered "CambridgeUI" style set (lazily initialised)
//   CambridgeUI::Brush("xp_titlebar")             any generated brush by file name
//   CambridgeUI::Text("Title")                    named text styles (CUI.<Name>)
//   CambridgeUI::MakeXPWindow(...) etc.           composite widgets used by the menu and the HUD
//
// Font sizes are Slate points (pixels = points * 4/3 at DPI scale 1). The pixel fonts are sharpest at
// 6 / 12 / 18 / 24 / 36 / 48 / 72 pt.

#pragma once

#include "CoreMinimal.h"
#include "Framework/SlateDelegates.h"
#include "Fonts/SlateFontInfo.h"
#include "Layout/Margin.h"
#include "Misc/Attribute.h"
#include "Styling/SlateTypes.h"
#include "Templates/Function.h"

class FSlateStyleSet;
class ISlateStyle;
class SWidget;
struct FSlateBrush;

/** Owns the "CambridgeUI" FSlateStyleSet and its composite fonts. */
class FCambridgeUIStyle
{
public:
	/** Registers the style (idempotent). Safe to call from module startup or lazily from Get(). */
	static void Initialize();
	/** Unregisters the style and releases the fonts. Also hooked to FCoreDelegates::OnEnginePreExit. */
	static void Shutdown();
	/** The style set; initialises it on first use. */
	static const ISlateStyle& Get();
	static FName GetStyleSetName();
	static bool IsInitialized();

	/** Directory the brushes / fonts are loaded from (absolute). */
	static FString GeneratedDir();
	static FString FontsDir();

private:
	static TSharedRef<FSlateStyleSet> Create();
	static TSharedPtr<FSlateStyleSet> StyleInstance;
};

namespace CambridgeUI
{
	// ------------------------------------------------------------------ lookups

	/** A generated brush by name (the PNG stem, e.g. "xp_button_normal", "light_red", "icon_flag_lg"). */
	const FSlateBrush* Brush(FName Name);
	/** A named colour ("Luna.Blue", "Luna.Face", "Glass.TextDim", "Race.Ahead", ...). */
	FLinearColor Color(FName Name);
	/** A named text style: Title, Heading, Label, LabelSelected, Value, Body, BodyDim, Small, Button,
	 *  ButtonPrimary, ButtonBig, Key, KeyDark, HudLabel, HudLabelBright, HudHint, Timer, TimerSmall,
	 *  DigitsInk, Speed, SpeedGhost, Gear, Countdown, CountdownGo, SplitAhead, SplitBehind, SplitAheadHud,
	 *  SplitBehindHud, ToastTitle, ToastBody, ResultTime, Ribbon, Tray, Fps. */
	const FTextBlockStyle& Text(FName Name);
	/** Button styles: "Button" (beige XP), "Button.Primary" (green Start), "Button.Blue" (Luna blue), "Button.Close" (red X). */
	const FButtonStyle& Button(FName Name);

	// ------------------------------------------------------------------ fonts (Slate points)

	FSlateFontInfo PixelFont(float Size, bool bBold = false);   // Silkscreen, digits from Press Start 2P
	FSlateFontInfo DigitsFont(float Size);                      // Press Start 2P (monospaced: timers)
	FSlateFontInfo DotsFont(float Size, bool bBlack = true);    // Doto dot-matrix (monospaced: speed, fps)
	FSlateFontInfo BodyFont(float Size, bool bBold = false);    // Open Sans
	FSlateFontInfo CondensedFont(float Size);                   // Open Sans Condensed Bold (HUD labels)

	// ------------------------------------------------------------------ XP chrome

	/** Luna window: soft shadow, blue title bar (icon + pixel title + red close button), beige face.
	 *  OnClose unbound hides the close button. bFlagStrip adds a checkered strip under the title bar. */
	TSharedRef<SWidget> MakeXPWindow(const TAttribute<FText>& Title, const TSharedRef<SWidget>& Content, FName Icon = NAME_None,
		FOnClicked OnClose = FOnClicked(), FMargin ContentPadding = FMargin(12.0f), bool bFlagStrip = false);

	/** Clickable XP push button (beige) or green Start-style primary button. */
	TSharedRef<SWidget> MakeXPButton(const TAttribute<FText>& Label, FOnClicked OnClicked, bool bPrimary = false, FName Icon = NAME_None, bool bBig = false);

	/** Non-interactive button look for the HUD (the cursor is hidden in game): bFocused pulses the yellow focus ring. */
	TSharedRef<SWidget> MakeXPButtonFace(const TAttribute<FText>& Label, bool bPrimary = true, const TAttribute<bool>& bFocused = true, FName Icon = NAME_None, bool bBig = true);

	/** Small beige < or > spinner button with a pixel chevron. */
	TSharedRef<SWidget> MakeSpinButton(bool bRight, FOnClicked OnClicked);

	/** Internet-Explorer-style tab. Lay tabs out in an SHorizontalBox with VAlign_Bottom slots, directly above an xp_panel. */
	TSharedRef<SWidget> MakeXPTab(const TAttribute<FText>& Label, FName Icon, const TAttribute<bool>& bActive, TFunction<void()> OnClicked);

	/** List row: Luna selection (with the yellow cursor bar) when selected, faint blue on hover. */
	TSharedRef<SWidget> MakeListRow(const TSharedRef<SWidget>& Content, const TAttribute<bool>& bSelected, TFunction<void()> OnClicked = nullptr);
	/** Text colour for a row label / value (white on the selection, black otherwise). */
	FSlateColor RowTextColor(bool bSelected);

	/** Inset white content panel (xp_panel). */
	TSharedRef<SWidget> MakeXPPanel(const TSharedRef<SWidget>& Content, FMargin Padding = FMargin(8.0f, 10.0f));

	/** XP taskbar: green start button (icon + label), middle content, blue tray with text. 40 high. */
	TSharedRef<SWidget> MakeTaskbar(const TAttribute<FText>& StartLabel, const TSharedRef<SWidget>& Middle, const TAttribute<FText>& TrayText);

	// ------------------------------------------------------------------ glass HUD

	/** Dark translucent glass (glass_panel / glass_panel_bottom / glass_pill). */
	TSharedRef<SWidget> MakeGlassPanel(const TSharedRef<SWidget>& Content, FMargin Padding = FMargin(16.0f, 12.0f), FName BrushName = TEXT("glass_panel"));

	/** HUD panel: Luna title-bar chip (icon, title, optional green badge, optional right widget) over a glass body. */
	TSharedRef<SWidget> MakeHudPanel(const TAttribute<FText>& Title, FName Icon, const TSharedRef<SWidget>& Content,
		const TAttribute<FText>& Badge = TAttribute<FText>(), const TSharedPtr<SWidget>& HeaderRight = nullptr, FMargin Padding = FMargin(18.0f, 10.0f, 18.0f, 14.0f));

	/** Glossy Luna badge with text ("LAP 1/2"). Brush: gear_badge_green / _blue / _red. */
	TSharedRef<SWidget> MakeBadge(const TAttribute<FText>& Label, FName BrushName = TEXT("gear_badge_green"));

	enum class ETail : uint8 { None, Up, Down };

	/** XP balloon tooltip: icon + bold title (+ optional widget on the right), body text below. */
	TSharedRef<SWidget> MakeToast(const TAttribute<FText>& Title, const TAttribute<FText>& Body, FName Icon = TEXT("icon_info"),
		ETail Tail = ETail::None, const TSharedPtr<SWidget>& TitleRight = nullptr, float WrapWidth = 360.0f);

	/** Balloon with a caller-built header row (e.g. split arrow + delta + "GATE 17") and optional body text. */
	TSharedRef<SWidget> MakeToastCustom(const TSharedRef<SWidget>& Header, const TAttribute<FText>& Body, ETail Tail = ETail::None, float WrapWidth = 360.0f);

	/** Appear animation (the website's window-open): scale FromScale -> 1 and fade in over Duration seconds.
	 *  Age = seconds since the content was shown (drive it from world / Slate time). */
	TSharedRef<SWidget> MakeAnimatedIn(const TSharedRef<SWidget>& Content, const TAttribute<float>& Age, float Duration = 0.15f, float FromScale = 0.94f);

	/** Key cap. Key "^" "v" "<" ">" draws a chevron; "pad_a" / "pad_b" draw the gamepad buttons. */
	TSharedRef<SWidget> MakeKeyCap(const FText& Key, bool bDark = true);
	/** Key caps followed by a label ("[R] Back on track"). bDark: for glass (white label) vs beige faces (black label). */
	TSharedRef<SWidget> MakeKeyHint(const TArray<FText>& Keys, const TAttribute<FText>& Label, bool bDark = true);

	/** Row of XP progress-bar blocks in a trough. SegmentBrush(i, N) names the lit brush of block i (seg_green ...). */
	TSharedRef<SWidget> MakeSegmentBar(const TAttribute<float>& Fraction, int32 NumSegments, TFunction<FName(int32, int32)> SegmentBrush,
		FVector2D SegmentSize = FVector2D(8.0, 14.0), float Gap = 3.0f, bool bDarkTrack = true);
	/** rpm colouring: green to 70 %, amber to 88 %, red above. */
	FName RpmSegment(int32 Index, int32 Num);

	/** Gear indicator: Luna badge (red when bWarning, e.g. reverse) with the gear in pixel digits and "GEAR". */
	TSharedRef<SWidget> MakeGearBadge(const TAttribute<FText>& Gear, const TAttribute<bool>& bWarning);

	/** Right-aligned Doto readout over unlit "ghost" dots (Ghost = "888" for a 3-digit speed). */
	TSharedRef<SWidget> MakeDotReadout(const TAttribute<FText>& Value, const FText& Ghost, FName TextStyle = TEXT("Speed"));

	/** Start-light gantry: NumLit discs on (red, or all green when bGreen). */
	TSharedRef<SWidget> MakeStartLights(const TAttribute<int32>& NumLit, const TAttribute<bool>& bGreen, int32 NumLights = 4);

	/** Big countdown digit / GO!. Phase = seconds since this digit appeared (0..1): pops from 1.6x to 1x, fades at the end. */
	TSharedRef<SWidget> MakeCountdownDigit(const TAttribute<FText>& Text, const TAttribute<float>& Phase, const TAttribute<bool>& bGo);

	/** Gold swallow-tail ribbon with text ("NEW BEST!"). */
	TSharedRef<SWidget> MakeRibbon(const TAttribute<FText>& Label);

	/** Slowly spinning gold starburst with the pixel trophy on top (results screen). */
	TSharedRef<SWidget> MakeTrophyBurst(float Size = 150.0f);

	/** Full-screen pixel confetti that falls for a few seconds (results screen, new best). Put it in a Fill overlay slot. */
	TSharedRef<SWidget> MakeConfetti(float Seconds = 8.0f);

	/** Glass pill FPS readout. */
	TSharedRef<SWidget> MakeFpsChip(const TAttribute<FText>& Fps, const TAttribute<FText>& Detail);
}
