// Copyright Epic Games, Inc. All Rights Reserved.

using UnrealBuildTool;

public class CambridgeRacer : ModuleRules
{
	public CambridgeRacer(ReadOnlyTargetRules Target) : base(Target)
	{
		PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;

		PublicDependencyModuleNames.AddRange(new string[] {
			"Core",
			"CoreUObject",
			"Engine",
			"InputCore",
			"EnhancedInput",
			"ChaosVehicles",
			"PhysicsCore",
			"UMG",
			"Slate",
			"Json"
		});

		PublicIncludePaths.AddRange(new string[] {
			"CambridgeRacer",
			"CambridgeRacer/SportsCar",
			"CambridgeRacer/OffroadCar",
			"CambridgeRacer/Impreza",
			"CambridgeRacer/Variant_OffRoad",
			"CambridgeRacer/Variant_TimeTrial",
			"CambridgeRacer/Variant_TimeTrial/UI"
		});

		PrivateDependencyModuleNames.AddRange(new string[] { "RenderCore", "RHI", "SlateCore", "AudioMixer", "ProceduralMeshComponent", "ImageCore" });   // frame timing (ShotTour, FPS overlay), Slate menu

		// "Luna Glass" UI (CambridgeUIStyle): loose fonts and brushes read from <Project>/UI at runtime.
		// Brushes are generated by tools/ui/make_ui_assets.py (gitignored); stage both folders in packaged builds.
		RuntimeDependencies.Add("$(ProjectDir)/UI/Fonts/...", StagedFileType.UFS);
		RuntimeDependencies.Add("$(ProjectDir)/UI/Generated/...", StagedFileType.UFS);

		// Uncomment if you are using Slate UI
		// PrivateDependencyModuleNames.AddRange(new string[] { "Slate", "SlateCore" });

		// Uncomment if you are using online features
		// PrivateDependencyModuleNames.Add("OnlineSubsystem");

		// To include OnlineSubsystemSteam, add it to the plugins section in your uproject file with the Enabled attribute set to true
	}
}
