// Generates reference results with the JS evaluator from the web preview (independent of the C++ code).
// Usage: node make_vectors.js > vectors.h      (node make_vectors.js --json > vectors.json for other ports)
let state = 777;
const rng = () => { let x = state; x = (x ^ (x << 13)) >>> 0; x = (x ^ (x >>> 17)) >>> 0; x = (x ^ (x << 5)) >>> 0; return (state = x); };
function shuffle() {
  const c = [...Array(52).keys()];
  for (let i = 51; i > 0; i--) { const j = rng() % (i + 1); [c[i], c[j]] = [c[j], c[i]]; }
  return c;
}
function bjTotal(cards) {
  let sum = 0, aces = 0;
  cards.forEach(c => { const r = c % 13; sum += r < 8 ? r + 2 : r < 12 ? 10 : 11; if (r === 12) aces++; });
  while (sum > 21 && aces) { sum -= 10; aces--; }
  return sum;
}
function evalCards(c) {
  const cnt = new Array(13).fill(0);
  c.forEach(x => cnt[x % 13]++);
  const g = [];
  for (let k = 4; k >= 1; k--) for (let r = 12; r >= 0; r--) if (cnt[r] === k) g.push(r);
  const flush = c.length === 5 && c.every(x => Math.trunc(x / 13) === Math.trunc(c[0] / 13));
  let high = -1;
  if (g.length === 5) { if (g[0] - g[4] === 4) high = g[0]; else if (g[0] === 12 && g[1] === 3) high = 3; }
  let cat;
  if (high >= 0 && flush) cat = 8;
  else if (cnt[g[0]] === 4) cat = 7;
  else if (cnt[g[0]] === 3 && cnt[g[1]] >= 2) cat = 6;
  else if (flush) cat = 5;
  else if (high >= 0) cat = 4;
  else if (cnt[g[0]] === 3) cat = 3;
  else if (cnt[g[0]] === 2 && cnt[g[1]] === 2) cat = 2;
  else if (cnt[g[0]] === 2) cat = 1;
  else cat = 0;
  let score = cat * 2 ** 20;
  if (high >= 0) score += high * 2 ** 16;
  else g.forEach((r, i) => { score += r * 2 ** (16 - 4 * i); });
  return score;
}
function bestHand(c) {
  if (c.length <= 5) return evalCards(c);
  let best = 0;
  for (let m = 0; m < 1 << c.length; m++) {
    const pick = c.filter((_, i) => (m >> i) & 1);
    if (pick.length === 5) best = Math.max(best, evalCards(pick));
  }
  return best;
}

const N = 500, rows = [];
for (let i = 0; i < N; i++) {
  const h = shuffle().slice(0, 7);
  rows.push({ cards: h, bj3: bjTotal(h.slice(0, 3)), eval5: evalCards(h.slice(0, 5)), best7: bestHand(h) });
}
if (process.argv.includes('--json')) console.log(JSON.stringify({ seed: 777, rows }));
else if (process.argv.includes('--rust')) {
  console.log('// Generated by cpp_arduino_ide/qpad_casino/tests/make_vectors.js from the JS reference evaluator.');
  console.log(`pub const SEED: u32 = 777;\npub const VECTORS: [([u8; 7], i32, u32, u32); ${N}] = [`);
  rows.forEach(r => console.log(`    ([${r.cards.join(', ')}], ${r.bj3}, ${r.eval5}, ${r.best7}),`));
  console.log('];');
}
else {
  console.log('// Generated by make_vectors.js from the JS reference evaluator. Do not edit.');
  console.log('struct Vec { uint8_t cards[7]; int bj3; uint32_t eval5, best7; };');
  console.log(`const uint32_t VEC_SEED = 777;\nconst Vec VECTORS[${N}] = {`);
  rows.forEach(r => console.log(`  {{${r.cards.join(', ')}}, ${r.bj3}, ${r.eval5}u, ${r.best7}u},`));
  console.log('};');
}
